# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# read auth0 credentials from secretsmananger.
data "aws_secretsmanager_secret_version" "auth0" {
  secret_id = "auth0"
}
# parse auth0 credentials to use in auth0 provider below.
locals {
  auth0_client_id     = jsondecode(data.aws_secretsmanager_secret_version.auth0.secret_string)["client_id"]
  auth0_client_secret = jsondecode(data.aws_secretsmanager_secret_version.auth0.secret_string)["client_secret"]
}
provider "auth0" {
  domain        = "dniel.eu.auth0.com"
  client_id     = local.auth0_client_id
  client_secret = local.auth0_client_secret
}
provider "kubernetes" {
  config_context = var.kube_config_context
  config_path = var.kube_config_path
}
provider "kubernetes-alpha" {
  config_context = var.kube_config_context
  config_path = var.kube_config_path
}
provider "helm" {
  kubernetes {
    config_context = var.kube_config_context
    config_path = var.kube_config_path
  }
}
provider "aws" {
  region = var.aws_region
}
